apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - prometheus.yaml
configMapGenerator:
  - name: prometheus-config
    namespace: monitoring
    files:
      - prometheus.yml
      - rules.yml
